version: "3.8"

services:
  web:
    build: .
    container_name: react_app
    expose:
      - "80"
    environment:
      - PORT=80
    networks:
      - app-network

networks:
  app-network:
    external: true